a<-matrix(c(1:16),nrow=4,ncol=4,byrow=TRUE)
print("The matrix A is : ")
print(a)
print("The matrix B is : ")
b<-matrix(c(17:32),nrow=4,ncol=4,byrow=TRUE)
print(b)
print("Addition: ")
print(a+b)
print("Difference: ")
print(a-b)
print("Regular multiplication: ")
print(a%*%b)
print("Elements wise multiplication: ")
print(a*b)
print("Elements wise division: ")
print(a/b)